spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: adel
    password: passer123
    url: jdbc:postgresql://10.42.1.204:5432/document
    hibernate.ddl-auto: create
  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    #show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
