spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      username: adel
      password: passer123
      url: jdbc:postgresql://${DB_HOST:10.42.1.204}:${DB_PORT:5432}/${DB_NAME:document}
      hibernate.ddl-auto: create
